version: '3.7'
# https://docs.docker.com/compose/compose-file/compose-file-v3/

services:
  data-distillery-ubkg-api:
    hostname: data-distillery-ubkg-api
    container_name: data-distillery-ubkg-api
    ports:
      - "6667:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Use the published image from DockerHub instead of local build
    # Exit with an error message containing err if UBKG_API_VERSION is unset or empty in the environment
    image: ubkg-api:${UBKG_API_VERSION:?err}
    # Avoid accidentally creating zombie processes
    init: true
    # Specifying a restart policy to avoid downtime
    restart: always
    environment:
      # UID and GID 1001 to match the hive user by default
      - HOST_GID=${HOST_GID:-1001}
      - HOST_UID=${HOST_UID:-1001}
    networks:
      - gateway_hubmap
    volumes:
      # Mount the logging to container
      - "../log:/usr/src/app/log"
      # Mount the app config to container in order to keep it outside of the image
      - "../src/instance:/usr/src/app/src/instance"
      # Mount conf.d on host machine to the nginx conf.d on container
      - "./ubkg-api/nginx/conf.d:/etc/nginx/conf.d"

networks:
  gateway_hubmap:
    external: true